version: '3'

services:
  urlapp:
    build:
      context: .
    image: sayaliupasani/urlapp:1.0
    environment:
      - FLASK_ENV=development
    networks:
      - url_net
    volumes: 
      - ./app/:/url_status_project

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: sayaliupasani/nginx_proxy:1.0
    ports:
      - 80:80
    networks:
      - url_net
    volumes:
      - ./nginx/data:/etc/nginx/conf.d

networks:
  url_net:


